export const IS_LOGIN = '1'
export const IS_NOT_LOGIN = '2'
export const SET_USER_INFO = '3'
export const APPEND_FAVORITE = '4'
export const RESET_FAVORITE = '5'
export const SET_FAVORITE = '6'
export const SET_UNFAVORITE = '7'